.\" dvsink-command.1 written by Ben Hutchings <ben@decadent.org.uk>
.TH DVSINK-COMMAND 1 "18 February 2009"
.SH NAME
dvsink-command \- command sink for DVswitch
.SH SYNOPSIS
.HP
.B dvsink-command
.RI [ OPTIONS "] " COMMAND ...
.SH DESCRIPTION
.LP
Pass the output from DVswitch to another command.  The output will
appear as its standard input.
.SH OPTIONS
\fB\-h\fR, \fB\-\-host=\fIHOST\fR
.TP
\fB\-p\fR, \fB\-\-port=\fIPORT\fR
.RS
Specify the network address on which DVswitch is listening.  The host
address may be specified by name or as an IPv4 or IPv6 literal.
.RE
.SH AUTHOR
Ben Hutchings <ben@decadent.org.uk>.
.SH SEE ALSO
/usr/share/doc/dvswitch/README
