.\" dvsource-dvgrab.1 written by Ben Hutchings <ben@decadent.org.uk>
.TH DVSOURCE-DVGRAB 1 "24 May 2009"
.SH NAME
dvsource-dvgrab \- Firewire and Video4Linux2 sources for DVswitch
.SH SYNOPSIS
.HP
.B dvsource-firewire
.RI [ OPTIONS ]
.RB [ \-c
.IR CARD-NUMBER " | " DEVICE ]
.HP
.B dvsource-v4l2-dv
.RI [ OPTIONS "] [" DEVICE ]
.SH DESCRIPTION
.LP
\fBdvsource-firewire\fR uses \fBdvgrab\fR(1) to stream from a DV
device (camera or VCR) connected by Firewire.
.LP
\fBdvsource-v4l2-dv\fR uses \fBdvgrab\fR(1) to stream from a DV device
that has a Video4Linux2 driver.  This includes most USB DV cameras if
you have the uvcvideo driver installed.
.SH OPTIONS
\fB\-t\fR, \fB\-\-tally\fR
.RS
Print notices of activation and deactivation in the mixer, for use
with a tally light.  These will take the form "TALLY: on" or "TALLY:
off".
.RE
.TP
\fB\-h\fR, \fB\-\-host=\fIHOST\fR
.TP
\fB\-p\fR, \fB\-\-port=\fIPORT\fR
.RS
Specify the network address on which DVswitch is listening.  The host
address may be specified by name or as an IPv4 or IPv6 literal.
.RE
.TP
\fB\-c\fR, \fB\-\-card=\fICARD-NUMBER\fR
.RS
Specify the index of the Firewire card the DV device is connected to.
.RE
.SH AUTHOR
Ben Hutchings <ben@decadent.org.uk>.
.SH SEE ALSO
dvgrab(1), /usr/share/doc/dvswitch/README
