.\" dvswitch.1 written by Ben Hutchings <ben@decadent.org.uk>
.TH DVSWITCH 1 "18 February 2009"
.SH NAME
dvswitch \- mixes and distributes DV streams
.SH SYNOPSIS
.HP
.B dvswitch
.RI [ OPTIONS ]
.SH DESCRIPTION
.LP
DVswitch is a basic video mixer designed for use at conferences that
require live mixing for streams and/or recording.  It presents a GUI
for interactive control and runs a network server for connection of
sources and sinks.
.LP
The GUI is documented in the \fBREADME\fR file.
.SH OPTIONS
\fB\-h\fR, \fB\-\-host=\fIHOST\fR
.TP
\fB\-p\fR, \fB\-\-port=\fIPORT\fR
.RS
Specify the network address on which to listen and accept source
and sink connections.  The host address may be specified by name
or as an IPv4 or IPv6 literal.
.RE
.SH AUTHOR
Ben Hutchings <ben@decadent.org.uk>.
.SH SEE ALSO
gtk-options(7), /usr/share/doc/dvswitch/README
